delete from PlayerGroup;
delete from PlayerSet;
delete from PlayerTournament;
delete from [Set];
delete from PlayerGame;
delete from Game;
delete from [group];
delete from Player;
delete from Tournament;
